import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [

  {
    path: "",
    title: "Menú",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  {
    path: "",
    title: "CRUDS",
    moduleName: "forms",
    iconType: "feather",
    icon: "layout",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "/empresas/list",
        title: "Empresas",
        moduleName: "empresas",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: [],
      },
      {
        path: "/empleados/list",
        title: "Empleados",
        moduleName: "forms",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: [],
      },
    ],
  },
];
